columns:
- TIME_STAMP
- CDR_ID
- SESSION_ID
- CORRELATION_SESSION_ID
- CORRELATION_USER_SESSION_ID
- MEASURING_PROBE_NAME
- MEASURING_PROBE_LOC_ID
- MEASURING_PROBE_TYPE
- START_TIME
- NER
- SOURCE_IP_PORT
- DEST_IP_PORT
- SOURCE_IP
- DEST_IP
- SOURCE_MASK_IP
- DEST_MASK_IP
- FILTERED_SOURCE_IP
- FILTERED_DEST_IP
- FILTERED_OUT_RTP_DEST_IP
- SOURCE_NE_NAME
- DEST_NE_NAME
- SIGNALING_FILE_NAME
- DEST_ALIAS_FULL
- SOURCE_PHONE_NUMBER
- DEST_PHONE_NUMBER
- CALL_TYPE
- TERMINATION_CAUSE
- QMANAGER_TIME_STAMP
- EVENT_TYPE
# - COUNTER
- END_TIME
- MERGE_FLAG
- IN_MERGE_CACHE
- OUT_MERGE_CACHE
- MEASURING_PROBE_NAME_1
- MEASURING_PROBE_NAME_2
- RELEASE_CAUSE
- SENT_INITIAL_CDR
- PROCEDURE_DURATION
- CALLING_PARTY_SUFFIX
- COMMAND_CODE
- FAILED_AVP
- SERVER_ASSIGNMENT_TYPE
- SERVER_AUTHORIZATION_TYPE
- DEREGISTRATION_REASON_CODE
- DEREGISTRATION_REASON_INFO
- SOURCE_ALIAS_FULL
- IMS_USER_STATE
- SCSCF_NAME
- USER_STATE
- PSI_ACTIVATION
- SERVICE_LEVEL_TRACE_INFO
- SUBS_REQ_TYPE
- EXPIRY_TIME
- NOTIF_EFF
- ACCOUNT_SESSION_ID
- AUTHENTICATION_CONTEXT
- SERV_PRO_CORRELATION_ID
- AUTHENTICATE
- MN_NAI
- SERVICE
- CALLING_PARTY
- CLASSIFICATION_TYPE
- IMSI
- IMEI
- MSISDN
- APN
- TAC
- PLMN_IDENTITY
- MCC
- MNC
- RAT_TYPE
- KASME
- CONNECTION_TYPE
- MANUFACTURER
- MODEL
- ORIGIN_REALM
- DESTINATION_REALM
- ORIGIN_REALM_NAME
- DESTINATION_REALM_NAME
- TOTAL_UL_FRAMES
- TOTAL_DL_FRAMES
- TOTAL_BYTES_SEND_BY_MS
- TOTAL_BYTES_RECEIVED_BY_MS
- ORIGIN_HOST
- DESTINATION_HOST
- APPLICATION_ID
- REQUEST_TYPE
- APN_SERVICE
- TAC_CATEGORY
- MS_IP_ADDRESS
- MSG_COUNT
- PROCEDURE_TYPE
- IMPU
- RAT_TYPE_NAME
- ERROR_MESSAGE
- REQUEST_NUMBER
- TDF_APPLICATION_ID
- AUTH_APPLICATION_ID
- ORIGIN_STATE_ID
- IP_CAN_TYPE
- SESSION_RELEASE_CAUSE
- EVENT_TRIGGER
- LAC
- RAC
- SAC
- CGI
- TAI_TAC
- RAI
- CALLED_STATION_ID
- CHARGING_ID
- FRAMES_COUNT
- IMS_CHARGING_ID
- NUMBER_OF_REQUESTS
- NUMBER_OF_RESPONSES
- NUM_OF_RETRANSMISSION_FRAMES
- TRANSPORT_LAYER_PROTOCOL
- VLAN_ID
- PROCEDURE_SUBTYPE
- ORIGIN_HOST_NAME
- DESTINATION_HOST_NAME
- ACCOUNTING_RECORD_TYPE
- CONVERSION_AUTH_SESSION_STATE
- UNIQUE_CDR_ID
- MCPTT_PARTY_ID
- CALLED_PARTY
- TMGI
- APN_AMBR_DL
- APN_AMBR_UL
- CHARGING_RULE_NAME
- CHARGING_RULE_BASE_NAME
- CHARGING_RULE_BASE_NAME_INSTAL
- CHARGING_RULE_BASE_NAME_REMOVE
- CHARGING_RULE_BASE_NAME_DEF
- MCPTT_GROUP_ID
- MCPTT_SUBSCRIBER_ID
- DRA_IP_ADDRESS
- DRA_COUNT
- NUM_OF_HOPS
- NUM_OF_COMPLETED_HOPS
- HOP_BY_HOP
- END_TO_END
- SUBSCRIPTION_ID
- PUBLIC_IDENTITY
- USER_IDENTITY
- TRANSPORT_LAYER_PROTOCOL_LIST
- VLAN_ID_LIST
- TMGI_HEX
- STN_SR
- DSCP
- DEST_DSCP
- CORRELATION_SESSION_IDS
- FRAMES_COUNT_SAVED
primary_key: CDR_ID
table_name: CDR_HPA_DIAMETER
